### ISSUE TITLE
Не удается добавить Активность, выдает ошибку 

### ISSUE THREAD

**Issue by Galoev** [Ilkin-Galoev/nutritionist-helper#10]
("Error: in ", "unsigned int DatabaseModule::addActivity(const ActivityEntity &)", " Parameter count mismatch")

**Comment by fostfox** [comment]
Проблема заключалась в расхождении реального названия поля в таблице БД (файл db.sqlite), от того, который был указан в программе. 
_Очередной плюсик в поддержку переделки текущей архитектуры модуля работы с БД._

@Ilkin-Galoev, Когда проблема точно будет решена, необходимо слить ветку в `gui-midi`

**Comment by ArnMips** [comment]
Когда проблема точно будет решена, необходимо слить ветку в `gui-midi`
