### ISSUE TITLE
Нужно добавить поле для класса ProductEntity 

### ISSUE THREAD

**Issue by Galoev** [Ilkin-Galoev/nutritionist-helper#5]
В этом поле должно хранится в чем измеряется продукт: гр или мл

**Comment by fostfox** [comment]
@Ilkin-Galoev, сейчас эта функциональность в `class WeightedProduct`, что да, не логично. 
Нужно перенести ее в `class ProductEntity`

**Comment by fostfox** [comment]
Поле **перенесено** в `class ProductEntity`

**Comment by fostfox** [comment]
@Ilkin-Galoev, Закрыто
